eks/managing_user_access.md
This document outline how a cluster admin may manage providing cluster access to other team members
=> [SEVER-269] adding documentation for managing cluster user access in eks

gke/private_kubernetes/main.tf, gke/terraform.tfvars.template
Fixes a variable naming issue in the tfvars template and the missing
network policy provider for the k8s cluster which could cause a
terraform error
=> Fix two minor issues

eks/cluster.tf, eks/nomad/main.tf, eks/terraform.tf
use variables directly, put provider versions in requried_providers block
=> [SERVER-91] update deprecated syntax

.circleci/config.yml, README.md, eks/README.md, gke/README.md
Update documentation and pipeline to reflect new recommended terraform version
=> [SERVER-91] Terraform 0.14.2

README.md
=> Typo: createing -> creating

eks/bastion.tf, gke/private_kubernetes/extra-vms.tf
For both envs updated the following:
- kubectl
- kustomize
- kots
- kots/troublshoot.sh (preflight checks)
=> [SERVER-91] updated software on the bastion

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/variables.tf
https://circleci.atlassian.net/browse/SERVER-1308
We don't yet have an ASG for Nomad within AWS.
Added an ASG.
=> AWS Nomad ASG

nomad-gcp/main.tf, nomad-gcp/variables.tf
Shared VPCs need some distinction of where the host project and network
Adding support for selecting a host project
=> Adding support for shared VPCs in GCP

nomad-aws/README.md, nomad-aws/examples/basic/main.tf, nomad-gcp/README.md, nomad-gcp/examples/basic/main.tf
Now that we've added support for generating nomad auto-scaler keys. we need to document it
Added documentation for generating nomad-autoscaler keys
=> [server-1469] adding nomad-austoscaler to readme and example

nomad-aws/output.tf
[SERVER-1570](https://circleci.atlassian.net/browse/SERVER-1570)
:white_check_mark: **Fix** 
* Added Nomad Autoscaler Group ARN in output
=> Added Nomad ASG ARN in terraform output

nomad-gcp/README.md
No Jira | Removing extra " from Readme 
=> no-jira | removing extra "

nomad-aws/README.md, nomad-aws/examples/irsa/main.tf
Add AWS IRSA example - [SERVER-1658](https://circleci.atlassian.net/browse/SERVER-1658)
- Added example in the example folder
- Updated Readme
=> server-1658 | Added AWS IRSA example

nomad-aws/template/nomad-startup.sh.tpl, nomad-gcp/templates/nomad-startup.sh.tpl
The version of the Docker Engine is not up-to-date. We would like to incorporate the fixes in [20.10.10](https://docs.docker.com/engine/release-notes/#201010).
Latest version
https://docs.docker.com/engine/release-notes/#201014
Update Docker Engine version from 20.10.7 to 20.10.14 on nomad-startup.sh.tpl.
=> Update Docker Engine version to 20.10.14

nomad-gcp/main.tf
[SERVER-1966](https://circleci.atlassian.net/browse/SERVER-1966)
* Include Name in created resources
=> server-1966 | include name in created resources

nomad-gcp/output.tf
[SERVER-1969](https://circleci.atlassian.net/browse/SERVER-1969)
* Fixed base64 output var
=> server-1969-fix-base64-var | fix output var for base64

nomad-gcp/nomad-autoscaler.tf, nomad-gcp/output.tf, nomad-gcp/variables.tf
This PR supports adding custom project IDs as a variable, and outputting the service account JSON for GCP nomad.
=> Supporting custom project ID, outputting service account JSON

nomad-gcp/output.tf
Just some slight formatting to fix our CI pipelines
=> Fix terraform fmt

README.md, nomad-aws/README.md, nomad-gcp/README.md
[SERVER-2041](https://circleci.atlassian.net/browse/SERVER-2041)
- updated examples
- removed BETA
=> server-2041 | updated readme

nomad-aws/variables.tf
Tags are in conflict if pass the `environment` tag in `instance_tags` variable
Rename `environment` tag to `nomad-environment` tag 
=> no_jira_rename_default_tags | rename default tag to avoid conflict

.circleci/config.yml, Makefile, nomad-aws/README.md, nomad-gcp/README.md, nomad-gcp/variables.tf, scripts/generate-docs.sh
[SERVER-2445]
Terraform module readme's can sometimes drift out of date.
- Adds the `make docs` command for local generation of docs before commit
- Adds a CI job for checking docs are up to date before merge.
Tested manually
[SERVER-2445]: https://circleci.atlassian.net/browse/SERVER-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SERVER-2445] Real Time Terraform Docs

.circleci/config.yml, Makefile
[ONPREM-205]
Adds tfsec for monitoring of static infrastructure code.
[ONPREM-205]: https://circleci.atlassian.net/browse/ONPREM-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ONPREM-205] - tfsec testing for server-terraform

nomad-aws/main.tf
https://circleci.atlassian.net/browse/ONPREM-508
* Added Basename in AWS resources
=> ONPREM-508 | added basename in aws resource

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/security_groups.tf, nomad-aws/variables.tf
Addresses issues (by fixing or ignoring where appropriate) raised by tfsec.
[ONPREM-524]
- Adds http_tokens required to metadata options for AWS EC2 machines
- Updates security group descriptions to be more verbose
- Moves security group IP ranges to variables for more specific customizations
[ONPREM-524]: https://circleci.atlassian.net/browse/ONPREM-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Addressing issues raised by tfsec

nomad-aws/template/nomad-startup.sh.tpl, nomad-gcp/templates/nomad-startup.sh.tpl
:gear: **https://circleci.atlassian.net/browse/ONPREM-878**
patching docker engine to address critical vulnerability.
https://www.docker.com/blog/docker-security-advisory-multiple-vulnerabilities-in-runc-buildkit-and-moby/#patches
=> updating docker version

LICENSE
=> ONPREM-417 | Adding Apache v2 license

nomad-aws/modules/nomad-server-aws/server.tf
we just missed the plumbing needed to enable or disable public IPs on nomad servers
=> nomad server can have public IPs

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/variables.tf
- Switching the public/private ip for Nomad Client is not possible
- Added the `network_interfaces` block with the IP config
=> ONPREM-2201 | update nomad client public ip

nomad-aws/examples/externalized-nomad-servers/main.tf
adding nomad server externalization example for AWS
=> adding aws example for externalized nomad servers

nomad-aws/modules/nomad-server-aws/templates/nomad-server-startup.sh.tpl, nomad-aws/template/nomad-startup.sh.tpl, nomad-gcp/modules/nomad-server-gcp/templates/nomad-server-startup.sh.tpl, nomad-gcp/templates/nomad-startup.sh.tpl
This reverts commit 40d18aa9a143a9c03432c5f98da8096ddfba07c9.
=> Revert "enable mtls for http (#220)"

nomad-gcp/main.tf
=> Fix subnetwork check in nomad-gcp/main.tf

nomad-gcp/main.tf
=> Fix syntax of CIDR range for Nomad clients

nomad-aws/template/nomad-startup.sh.tpl, nomad-gcp/templates/nomad-startup.sh.tpl
replacing the deprecated client options for drivers with a plugin for raw_exec
https://developer.hashicorp.com/nomad/docs/drivers/raw_exec#client-options
https://circleci.atlassian.net/browse/ONPREM-2238
=> adding a plugin for raw_exec

.circleci/config.yml, nomad-aws/examples/irsa/main.tf, nomad-aws/modules/nomad-server-aws/output.tf, nomad-aws/output.tf, nomad-aws/tests/basic.tftest.hcl, nomad-aws/tests/externalized_servers.tftest.hcl, nomad-gcp/modules/nomad-server-gcp/output.tf, nomad-gcp/modules/nomad-server-gcp/server.tf, nomad-gcp/tests/basic.tftest.hcl, nomad-gcp/tests/externalized_servers.tftest.hcl
Jira: https://circleci.atlassian.net/browse/ONPREM-2292
This PR updates the CI to validate all Nomad examples, as well as introduces `terraform test`, which seems to catch more stuff than `terraform validate`. It pretty much renders everything short of doing `terraform plan` using mock providers. Issues discovered by both were also fixed in this PR.
=> [ONPREM-2292] Add Terraform tests
