eks/bastion.tf, gke/private_kubernetes/extra-vms.tf
We are using an older version of kots that consistently fails at
applying our current replicated releases due to annotations being added
to all kubernetes resources regardless of if they are mutable or
immutable.
Later versions of kots no longer add this annotation and we
should use them instead. This commit bumps the version of kots to the
latest version as of this commit.
=> (RE-779) Update kots versions

gke/README.md, gke/main.tf, gke/nomad/main.tf, gke/nomad/variables.tf, gke/terraform.tf, gke/variables.tf
**Problem**
We currently demand that GCP users specify a service account credentials file. These is fairly rigid in that it requires users to create a service account with sufficient permissions and an associated key file even if they already have sufficient permissions themselves and application default credentials set up.
**Solution**
Use the Terraform google provides built-in credential discovery and remove the explicit need to specify a service-account file.
**Test Checklist**
**Post merge checklist**
=> Simplify Google Auth

eks/cluster.tf, eks/terraform.tfvars.template, eks/variables.tf
The number of nodes and the machine type used was hardcoded to the cluster.tf file the eks dir.
This PR replaces those values with variables so the user may tune the cluster specs to their needs from the tfvars file. defaults have been set which match our existing hardcoded values.
=> [NO JIRA] replacing hardcoded node number values with variables

eks/README.md, eks/terraform.tfvars.template, eks/variables.tf, gke/README.md
Changes:
- remove references to kots, kustomize and helm
- eks no longer requires pgp key
- the link for kubectl assumes an OS. replacing with more general
instructions
=> [No JIRA] Documentation Updates

gke/README.md, gke/nomad/nomad.tf
SERVER-102
I left the service account itself in case a given operator
wants to apply some privileges to the nomad clients. However,
by default, we don't need any of the previously defined permissions.
They were just a holdover and copy/paste error from the GKE cluster.
=> Remove Service Account permissions from Nomad

gke/private_kubernetes/extra-vms.tf
The bastion host was using the GKE cluster's Service Account, which was way too
powerful. This adds a separate SA for the bastion. As we are using OS Login on
the bastion (see #29), this SA has no special permissions, ensuring that the user cannot
perform any actions outside their own permissions by impersonating the
instance's SA.
Tested:
[x] I can still SSH into the bastion
[x] I can still renew my credentials for kubectl and perform actions on the
cluster (like deleting pods, editing deployments)
[x] I can still SSH into Nomad clients from the bastion
=> Add separate Service Account to bastion host

eks/bastion.tf, eks/cluster.tf
if you're not running a bastion server, then you don't need:
- the bastion IAM role
- the bastion IAM policy
- the bastion instance profile
- the bastion IAM role among the k8s_roles
=> check for bastion in a few more places

eks/nomad/main.tf
The terraform-aws-autoscaling module automatically sets it's own "Name" tag so the nomad module shouldn't.
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/locals.tf#L2-L12
Without this whenever you run terraform plan it will show a difference every time.
=> the Autoscaling module already sets the Name tag

eks/terraform.tf, eks/variables.tf
In our setup we have 10 profiles installed locally, each one pointing to
a different account. The CircleCI setup is in a specific non-default
one, so having the ability the specify it is needed, otherwise you need
to remember to run:
```
export AWS_PROFILE=profile_name
```
=> Actually use the aws_profile variable

eks/cluster.tf, eks/variables.tf
Some users/companies login to AWS via SAML and that means that IAM roles are used to
identify them and not IAM users.
=> Allow defining Kubernetes admins using Roles

gke/private_kubernetes/main.tf
Adds [Calico](https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy#using_network_policy_enforcement) as a network policy enforcer to GCP.
- Ticket: SERVER-565
- Change: Security enhancement
- Testing checklist:
=> Add Calico network policy enforcement to GCP

.gitignore, gke/README.md, gke/main.tf, gke/managing_user_access.md, gke/nomad/nomad.tf, gke/nomad/variables.tf, gke/private_kubernetes/extra-vms.tf, gke/private_kubernetes/firewalls.tf, gke/private_kubernetes/main.tf, gke/private_kubernetes/variables.tf, gke/terraform.tfvars.template, gke/variables.tf
This commit enables proper and secure user management in GKE by ensuring
that:
* The configuration defaults to a bastion host
* SSH keys are managed via GCP IAM mechanisms
* Process around using K8s RBAC with GCP IAM is documented
To ensure that the bastion host is actually secure, the following
changes were added when using a bastion host:
* Access to bastion can be restriced using allowed CIDR blocks
* All other access via the public internet is removed when bastion is
used
* Documentation was updated accordingly
=> User management for GKE

eks/nomad/main.tf
On GKE the autoscaling resource is separate from the compute resource.  We have not implemented the autoscaler yet, so this is a non issue there.
In EKS, we provide users a variable to set their desired node count, but not the min and max.  This means they could set it outside the min/max range breaking things.  We could also expose those as variables for user config, but autoscaling is not implemented at all right now, so it would just be misleading to the users.
The current setting also made it easy for us to make changes outside of the terraform, which is bad.  This incoming change also helps address that a little bit by making the user think twice about an edit in the AWS console
This will need to be implemented as a user configurable setting as part of implementing autoscaling.
=> set all nomad autoscaling values the same.  there is no autoscaling implemented anyway

gke/main.tf, gke/private_kubernetes/extra-vms.tf, gke/private_kubernetes/variables.tf, gke/variables.tf
This adds an option to have a privileged bastion host service account as we need it for our CI pipeline. PRs updating our `terraform.tfvars` in our assets repos are to follow.
=> Add privileged bastion option

eks/nomad.tf, eks/nomad/main.tf, eks/nomad/variables.tf, eks/variables.tf, eks/vpc.tf
In our AWS accounts we do lots of VPC Peering and the CircleCI VPC specifically is peered with other VPCs for service access, like GHE and our own private package repositories, so having the ability to customize the IP address ranges for the VPC is necessary.
In 96d8a0b removed the previous aws_subnet_cidr_block variable as it was only used on the Nomad security group to isolate access from the Nomad servers, which should be the whole VPC CIDR block anyway.
=> allow custom VPC CIDR addresses

eks/.gitignore, eks/cluster.tf
We're currently using instance profile (i.e. IMDS endpoint on EKS nodes) to give AWS credentials to Server services. We'd like to move completely away from this in the future, but in the interim this update to the policies restricts privileges to what is necessary to function.
- Ticket: [SERVER-566](https://circleci.atlassian.net/browse/SERVER-566)
- Change type: Security Improvement 🛡️ 
- Test checklist:
=> Restrict IAM permissions on EKS nodes

gke/private_kubernetes/main.tf, gke/terraform.tf
Easy stuff first:
- Removed commented out code block
- updated the Providers to the most recent version
- removed `version_prefix` because it is not doing anything when we specify a version by the channel
Less easy stuff:
- EKS is on k8s version 1.18.  1.18 is not yet available in all regions for GKE, so we cannot use it.
- It seems to be preferred to subscribe to a channel instead of specifying a version.  Read more about it [here](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels), a notable point is all channels are considered safe for GA.  Updating to the Regular channel will get us to k8s version 1.17 today.  This is closer what runs on EKS.  Moving forward we will have to expect there will be discrepancies between the K8s versions on each provider.
Tested by …
=> [SERVER-91]use Regular GKE channel, update Google provider

eks/nomad/main.tf, eks/outputs.tf, gke/main.tf, gke/nomad/nomad.tf, gke/nomad/variables.tf, shared/modules/tls/outputs.tf, shared/modules/tls/tls.tf, shared/modules/tls/variables.tf, shared/nomad-scripts/nomad-startup.sh.tpl
This adds mutual TLS encryption for Nomad server and clients. It generates a CA and
key/cert pairs. While the certs can be injected into the client via the
startup script, the certs for the server have to be copied into kots
config to get them into the cluster.
=> Add Nomad mTLS

gke/nomad/nomad.tf, shared/nomad-scripts/nomad-startup.sh.tpl
This adds iptable rules to Nomad clients preventing all docker jobs from
talking to the meta-data service or any internal IPs on the network. I
copied the assumption we make in the GKE k8s module that the internal
network will use a 10.0.0.0/8 block (or part thereof) for the internal
IPs.
I also added an additional firewall rule to allow the rerun-with-ssh
functionality for GKE clusters.
To test the functionality, I ran a pipeline that installed curl via apk
(ensuring that normal network traffic was still functional) and then
tried to curl meta-data from `169.254.169.254` which I expected to time
out, which was exactly what happened.
=> Secure Nomad clients via iptable rules

gke/nomad/nomad.tf
**Problem:**
When the bastion is enabled the firewall rule [immediately above](https://github.com/CircleCI-Public/server-terraform/blob/1a003422028c5a56b982341e546b4228327ced43/gke/nomad/nomad.tf#L93-L96) is also created and it has the same name.  Terraform returns an error stating the conflict.
**Solution:**
rename one of them
=> firewall names compete when bastion is enabled

shared/nomad-scripts/nomad-startup.sh.tpl
This fixes the iptables rules for EKS and supersedes PR #51. Pipelines ran successfully with these rules.
=> Fix iptables rules

eks/README.md, gke/README.md
Update documentation to match the new recommended kubectl version.
this documentation update was missed in the last PR.
=> [SERVER-91] update recomended kubectl version in the documentation

gke/main.tf, gke/private_kubernetes/firewalls.tf, gke/private_kubernetes/variables.tf, gke/terraform.tfvars.template, gke/variables.tf
VMs spun up by `vm-service` were open on several ports to
TCP traffic from the entire internet. This commit tightens access as
follows:
* Only allow access via bastion host by default. Access via the public
internet can be enabled via a variable
* If access via internet is enabled, restrict access to
`allowed_external_cidr_blocks`
Work to accomplish same in EKS is to follow
=> Tighten firewall for VMs in GKE

gke/private_kubernetes/firewalls.tf
As some communication between nomad clients, the cluster, and the external VMs is conducted via the public internet, we need to reinstate this firewall rule for all configurations for now. However, we hope to get this fixed on the product level, hence the variables introduced in the original PR remain in place for now.
=> Hotfix - fix external VMs

gke/nomad/main.tf, gke/nomad/output.tf
If you try to create a GKE cluster, currently this will fail for 2 reasons: 
- in `module.nomad_tls ? module.nomad_tls.nomad_server_key : ""`, module.nomad_tls does not evaluate to a boolean. To fix replace `module.nomad_tls` with `var.enable_mtls`
- the nomad_tls module return its attributes as a list so attributes need to be referenced with an index. eg: `module.nomad_tls[0].nomad_server_cert`
=> [No JIRA] fix data type errors in nomad module

eks/terraform.tfvars.template, eks/variables.tf
**Problem**:
changing the desired_capacity in terraform after initial creation does nothing
**Explanation**:
-  This is by design from the module used: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/835
- server-terraform does not yet support autoscaling.  Manually scaling needs to be done through the console at this time
- Supporting autoscaling will need to be done with this autoscaler: https://github.com/kubernetes/autoscaler
=> clarify desired_capacity must be changed in the console

shared/nomad-scripts/nomad-startup.sh.tpl
We should only be loading the TLS section if the cert is non-zero - the previous content had this logic inverted.
=> Invert the logic to only load SSL certs when they are non-zero

eks/s3.tf, gke/main.tf, gke/terraform.tfvars.template, gke/variables.tf
GCP buckets did not have the option to toggle force_destroy
Also an update to the S3 bucket tagging to reflect the state of force_destroy
=> [No JIRA] force_destroy was not configured for gke buckets

eks/s3.tf
This PR adds encryption to our S3 bucket. 
Output-processor however has a hard-coded policy within it which is used for server jobs. execution team needs to do work however to add kms permissions to the policy within output-processor. Once that work is done then we may merge this PR.
Tests:
How to test:
1. Spin up an instance of EKS using this branch
2. Deploy server 3.0 onto this cluster
3. Create a REPL to output-processor and apply the following to update the policy:
`(in-ns 'output-processing.storage)
(defn- aws-credentials-policy
[build project aws-identity]
(let [[bucket prefix] (str/split (artifacts-bucket) #"/" 2)
build-id (-> @build :_id str)
workspace-id (-> @build :workflows :workspace-id)
project-root (storage-root build project prefix)
test-results (:used-test-results @build) …
=> [SERVER-449] encrypting s3 bucket

shared/nomad-scripts/nomad-startup.sh.tpl
The if statement in the Nomad startup script didn't resolve correctly, leading to the Nomad clients not being able to connect to the server correctly
=> Fix Nomad startup script

eks/nomad.tf, eks/nomad/main.tf, eks/nomad/variables.tf, eks/terraform.tfvars.template, eks/variables.tf, shared/nomad-scripts/nomad-startup.sh.tpl
This adds an option to have Nomad clients deployed to a private subnet
with no public IPs assigned to them. The limitations this entails have
been documented in the `terraform.tfvars.template` file.
Furthermore, some typos were fixed and the k8s cluster node count
amended to satisfy increased preflight check demands
Checks conducted:
* Nomad clients don't have public IPs assigned to them
* Jobs can still be run successfully, even if they need to pull images etc
=> Add private Nomad client option

eks/cluster.tf, eks/managing_user_access.md, eks/terraform.tfvars.template, eks/variables.tf, gke/README.md, gke/managing_user_access.md, gke/terraform.tfvars.template, gke/variables.tf
This changes the default access pattern from a setup where resources are
private by default and can only be accessed via a bastion host to an
all-public approach. It is the user's responsibility to secure access to
their resources.
The documentation has been updated to reflect this.
Tests:
[x] Checked if clusters exhibit expected access restrictions on GKE, EKS
[x] Checked if modifying endpoint access in EKS is non-destructive
=> Use public k8s endpoint by default, disable bastion

gke/main.tf, gke/private_kubernetes/main.tf, gke/private_kubernetes/variables.tf, gke/variables.tf
The cloud is expensive! This work adds an option to use preemptible nodes in GCP to lower the cost of a Server deployment. This is primarily intended for development and pre-prod environments as we don't have perfect HA in Server yet.
- Ticket: None
- Change type: Cost control 💸 
- Testing checklist
=> Add option for preemptible nodes

eks/ami.tf, eks/nomad.tf, eks/nomad/variables.tf, eks/variables.tf, gke/nomad.tf, gke/nomad/main.tf, gke/nomad/variables.tf, gke/variables.tf, shared/nomad-scripts/nomad-startup.sh.tpl
This change sets the base image for the Nomad client to Ubuntu 20.04
Focal. The mechanism in which the image is selected has been altered.
Originally, we used the ubuntu_ami map located in the variables.tf
file located in the EKS root directory. The region would be passed
to the map and the proper AMI was derived from the map.
This change adds `ami.tf` which will perform a lookup against the
Ubuntu AWS AMI list and determine which AMI to use based on the
criteria set in the filter. This value is then made available to the
`ami_id` variable in the `nomad.tf` file.
The `ami_id` was slightly altered to allow the user to provide their
own AMI id. However, it defaults to the auto-selection outlined
above if the variable is not defined.
=> [SERVER-611] Set Nomad Client base AMI to Ubuntu 20.04 Focal

gke/main.tf, gke/nomad/main.tf, gke/private_kubernetes/firewalls.tf, gke/private_kubernetes/variables.tf, gke/variables.tf
This adjusts firewall rules in GCP to open the ports needed to SSH'ing
into jobs using 'rerun with SSH' on external VMs and also uses a
separate IP whitelist for permissible source CIDR blocks. This whitelist
defaults to 0.0.0.0/0
=> Fix firewall rules for SSH'ing into jobs [GCP]

gke/private_kubernetes/extra-vms.tf
We need to generate a support bundle in the ox-bot workflow pipeline where core services fails to deploy correctly
Add the support-bundle plugin and download the support-bundle for the failed CCI Application deployment in the pipeline
=> RE-774: Install support-bundle plugin on bastion

eks/README.md
Clone command in `## Setup` refers to incorrect org
=> Correct org name

eks/terraform.tf
Allow use of `aws` provider 3.10.0 or newer.
IIUC [recent change in AWS VPC Terraform module](https://github.com/terraform-aws-modules/terraform-aws-vpc/commit/4b83a66ef3eb0c7efc917f9c4dfee778b2002399) requires AWS provider 3.10.0 or newer, and without this patch `terraform init` will fail with the error message `Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints ~> 3.0.0, >= 3.10.*, ...`.
I confirmed that the latest beta version running on the infrastructure built with this patch passes `realitycheck`.
=> Accept newer AWS provider

shared/nomad-scripts/nomad-startup.sh.tpl
Use `mq-deadline` IO scheduler for root volumes of Nomad clients which are visible as a NVMe device. See [this internal Slack discussion](https://circleci.slack.com/archives/CAT9Q7TGW/p1611911848093000?thread_ts=1610548657.306800&cid=CAT9Q7TGW) for technical details.
=> Use mq-deadline IO scheduler for root volume

README.md
Query string must come after path in URI
=> Fix URI in README example

nomad-aws/main.tf, nomad-aws/template/nomad-startup.sh.tpl
We've attempted to keep a somewhat general nomad init script, but the details of even GCP versus AWS cause it to be pretty branch heavy. As we think about supporting more cloud providers, and perhaps even on-prem situations like vSphere, this will get more branch-y. 
Just make the nomad script private to the AWS specific module and don't make such attempts at being general.
=> AWS specific nomad script

nomad-aws/README.md
Folks unfamiliar with Terraform modules may not instinctively look in the `examples` directory for usage examples and the `examples` directory does not demonstrate how to reference the module using git (it uses relative directories instead). This might leave people a little confused on how to get started.
Add a simple usage example that matches our other documentation around how to use the nomad-aws module.
=> Add usage example to nomad-aws README

nomad-aws/main.tf, nomad-aws/versions.tf
The current iteration of nomad-aws user-data gets really close to the
maximum number of bytes that AWS allows for (it complains at around 21,600
bytes in base64 encoded format).
The use case is if someone forks this module and adds additional
content, they will very quickly hit that limit (which is what happened
to me)
The [cloudinit Terraform provider](https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs/data-sources/cloudinit_config) makes it pretty transparent to compress
and base64 encode user data, it resulted in a size reduction of 50% in
my case.
=> reduce user-data size for nomad-aws module

README.md, nomad-aws/README.md, nomad-aws/examples/basic/main.tf, nomad-aws/main.tf, nomad-aws/variables.tf, nomad-aws/versions.tf
This makes two changes to follow Terraform best practices for reusable modules:
* It removes the provider definition from the module: https://www.terraform.io/docs/language/modules/develop/providers.html
* It changes the way that version constraints are specified: https://www.terraform.io/docs/language/expressions/version-constraints.html
=> Updates to make nomad-aws a reusable module.

.circleci/config.yml, README.md, nomad-gcp/README.md, nomad-gcp/examples/basic/main.tf, nomad-gcp/main.tf, nomad-gcp/output.tf, nomad-gcp/templates/nomad-startup.sh.tpl, nomad-gcp/variables.tf, nomad-gcp/versions.tf
We want to support GCP nomad workers for GA and we currently don't.
Creates a module for creating nomad workers in GCP. Feature list
- CPU based autoscaling with customizable target utilization
- Cron scheduled scaling
- Preemptible nodes can be enabled (saves 💰 by using short lived nodes)
- Instance type and disk type modifiable
- Can enumerate allowed IP source addresses for "retry with ssh"
- Can enumarate destination IP addresses to block from nomad jobs
- mTLS
- Option to not assign public IP
The follow settings all pass reality check:
Additional tested features
=> GCP Nomad workers

nomad-gcp/README.md, nomad-gcp/main.tf, nomad-gcp/variables.tf
Unable to create multiple nomad clients pointing to the same network. This resulted in a firewall creation collision.
Added a var for the nomad client creation. Defaults to `nomad` still.
=> (maint) Add name var for gcp nomad clients

nomad-aws/template/nomad-startup.sh.tpl, nomad-gcp/templates/nomad-startup.sh.tpl
We want to collect nomad metrics for prometheus to scrape. Currently nomad-metrics exposes a custom set of nomad metrics. Enabling telemetry exposes the full list of nomad server metrics and is needed to access client metrics.
Enabled Telemetry on nomad clients to match server configs in this PR: https://github.com/circleci/server/pull/319
Validated that nomad metrics appear in prometheus
=> [SERVER-1023] Enable telemetry on Nomad client

nomad-aws/main.tf
When trying to use the module for AWS with Terraform v0.12 or later, you'd get an error like this:
```
Error: Error in function call> │> │ on .terraform/modules/nomad_clients/nomad-aws/main.tf line 36, in locals:> │ 36: nomad_security_groups = compact(list(> │ 37: aws_security_group.nomad_sg.id,> │ 38: var.ssh_key != null ? aws_security_group.ssh_sg[0].id : "",> │ 39: ))> │> │ │ aws_security_group.nomad_sg.id will be known only after apply> │ │ aws_security_group.ssh_sg[0].id will be known only after apply> │ │ var.ssh_key is a string, known only after apply> │> │ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```
Use the …
=> Fix list function

.circleci/config.yml, README.md, nomad-aws/README.md, nomad-aws/examples/basic/main.tf, nomad-aws/output.tf, nomad-gcp/output.tf, shared/modules/tls/outputs.tf
Our current terraform scripts require the use of nonsensitive which is only available in v0.15
https://circleci.atlassian.net/browse/SERVER-1164
Changed min terraform version to v0.15.4
Added nonsensitive to nomad tls key output
Related PRs
https://github.com/circleci/server/pull/851
https://github.com/circleci/circleci-docs/pull/5405
=> updating terraform required version to v0.15.4 or higher

nomad-aws/security_groups.tf
There was a superfluous ingress rule in the Nomad server ingress rules
remove the rule
=> Remove RPC ingress rule for nomad SG

nomad-aws/output.tf, nomad-gcp/output.tf
if mtls is disabled, terraform will fail. the nomad key output will be black which doesn't need to the `nonsensitive` function
`nonsensitive` is only used if mtls is enabled
=> bugfix - nonsensitive fails if MTLS is not enabled

nomad-aws/README.md, nomad-gcp/README.md
Customers have no way to make the connection between the docker resource classes and nomad instance types.
Reference the docker resource classes in the nomad terraform
docs only
If there is a better way to phrase it, please make the suggestion
=> [SERVER-1177] add details on how to choose an instance size

nomad-aws/template/nomad-startup.sh.tpl
Running docker 19.03.13 in nomad clients on AWS, but we'd like to run 20.10.07 to be in sync with cloud
Upgrade the docker version
=> SERVER-1289 | nomad-aws: Upgrade docker from 19.03.13 to 20.10.7

nomad-gcp/templates/nomad-startup.sh.tpl
Running docker 19.03.13 in nomad clients on GCP, but we'd like to run 20.10.07 to be in sync with cloud
Upgrade the docker version
=> SERVER-1289 | nomad-gcp: Upgrade docker to 20.10.07

nomad-aws/output.tf
coming from https://circleci.atlassian.net/browse/SERVER-1323 we need to expose the nomad security group id in the module output, allowing users to easily use the id in other security group ingress rules
added security group id to output
=> [SERVER-1323] adding nomad security group id to output

nomad-gcp/main.tf, nomad-gcp/templates/nomad-startup.sh.tpl, nomad-gcp/variables.tf
The `integration-workflow` nomad clients are no longer torn down after every workflow run. Since they will be created and left available for future workflow runs and the nomad server URI isn't immediately known. Having the `server_join` block in `config.hcl` leads to configuration issues.
This change creates a new terraform variable `add_server_join`, which defaults to `true`. When set to `false`, it omits the `server_join` block in the nomad client configuration file.
- `config.hcl` with `add_server_join` set to false:
- `config.hcl` with `add_server_join` not included in `terraform.tfvars` (defaults to `true`):
=> (RE-1204) Update nomad client config and create add_server_join var

nomad-aws/README.md, nomad-gcp/README.md
The documented examples had old versions (and even an RC), in addition to a typo in the GCP module.
=> Update to the 3.1 release

nomad-gcp/README.md
We have a typo that is pointing the GCP docs to the AWS module, which just yields errors.
Slight tweak in the README to use the GCP module.
=> Point GCP docs to the GCP module

nomad-aws/main.tf
SERVER-1435
We need to include the owner ID for Canonical's GovCloud account. This
small tweak allows the Terraform to run as expected in GovCloud.
=> GovCloud support

nomad-aws/examples/basic/main.tf, nomad-aws/main.tf, nomad-aws/nomad-autoscaler.tf, nomad-aws/output.tf, nomad-aws/template/nomad_asg_policy.tpl, nomad-aws/variables.tf
Our aws nomad terraform should create iam user creds for nomad auto-scaler
when when nomad_auto_scaler = true, aws terraform will now generate iam user creds for nomad-autoscaler
=> Server 1466

nomad-aws/README.md, nomad-gcp/README.md
Our examples in the readme's point to 3.1.0 however the latest release is 3.2.0
=> No jira/update module versions in readme

nomad-gcp/README.md, nomad-gcp/examples/basic/main.tf
:gear: **[Issue](https://circleci.atlassian.net/browse/SERVER-1538)**
We support deploying nomad clients in a shared vpc, but have not documented this
This PR updates our docs and examples
=> [server-1538] adding instructions for setting network and subnetwork when using a shared vpc

nomad-aws/README.md
The #96 removed `region` variable. But the variable is still present in README.md.
This PR removes the `region` variable from README.md.
=> Remove `region` input from README.md

nomad-aws/main.tf, nomad-aws/nomad-autoscaler.tf, nomad-aws/output.tf, nomad-aws/template/nomad_irsa_trust_policy.tpl, nomad-aws/variables.tf
Enable Terraform Code to create IAM Roles for Service Account (IRSA) 
* Added `nomad_auto_scaler (boolean)` to choose if we need Autoscaling feature
* Added `enable_irsa (map)` for IRSA specific inputs 
* `enable_irsa` is expecting 3 key values to create Role
* If nomad_auto_scaler is true then below conditioned will be checked - 
*  If the length of `enable_irsa` is greater than 0, terraform will create IRSA else Static User credentials will be created 
=> Added IRSA functionality in AWS code

nomad-aws/nomad-autoscaler.tf
resolves: https://github.com/CircleCI-Public/server-terraform/issues/132
related ticket: https://circleci.atlassian.net/browse/SERVER-1656
replaced `template_file` data source with `templatefile` function
=> nomad-aws now uses the templatefile function

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/variables.tf
Currently, an instance profile cannot be associated to instances of nomad clients on AWS. But there are cases when I want to associate an instance profile to the instance. (e.g. connect to the instances by Session Manager)
This PR adds an optional parameter `role_name`. If specified, an instance profile with the role is associated to nomad client instances.
=> Enable to associate instance profile to nomad client instance on AWS

nomad-gcp/README.md, nomad-gcp/examples/basic/terraform.tfvars_template, nomad-gcp/nomad-autoscaler.tf, nomad-gcp/variables.tf
Enabling Workload identity for k8s service account
Added Policy binding between GCP IAM service account and k8s service account
=> server-1557 | Add Policy binding in nomad autoscaler

nomad-aws/README.md
At least as of terraform v1.1.9, not doing so shows this error:
```
│ Error: Output refers to sensitive values
│
│   on main.tf line 49:
│   49: output "nomad" {
│
│ To reduce the risk of accidentally exporting sensitive data that was intended to be
│ only internal, Terraform requires that any root module output containing sensitive
│ data be explicitly marked as sensitive, to confirm your intent.
│
│ If you do intend to export this data, annotate the output value as sensitive by
│ adding the following argument:
│     sensitive = true
```
=> mark nomad tf output as sensitive

nomad-aws/main.tf, nomad-aws/variables.tf
[SERVER-1779](https://circleci.atlassian.net/browse/SERVER-1779). Instead of using launch configuration we should switch to launch templates. One advantage is easier versioning.
The `$Default` version will be used unless a specific version of a template is specified in variables.tf. The default version is the first version of the [template unless explicitly changed](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html). We also have the option to set the version to `$Latest` so that any new instance is on the latest version of the template.
➡️ Applying this change will cause the existing nomad client instances to roll. ⬅️ 
=> [SERVER-1779] Switch from using launch configuration to launch templates

nomad-aws/variables.tf
[SERVER-1845](https://circleci.atlassian.net/browse/SERVER-1845). 
Currently the `$Default` version of the launch template it used which translates to the **first** version of the template (unless set otherwise). This can create confusion when new instances come up and continue using old settings. The reason is not immediate apparent unless one understands the default [launch configuration](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html) details. Making sure that the latest template is always used makes more sense.
=> Default to the latest version of the nomad client launch template

nomad-gcp/README.md, nomad-gcp/examples/basic/main.tf, nomad-gcp/examples/docker_network/main.tf, nomad-gcp/variables.tf
our GCP docs do not:
- clarify that workload identities needs to be enabled on the GKE cluster to use the feature
- reference the single loadbalancer, instead it assumes there is a nomad subdomain
updated the docs
=> Server 1922 workload identity docs update

nomad-gcp/nomad-autoscaler.tf, nomad-gcp/output.tf, nomad-gcp/variables.tf
Reverts CircleCI-Public/server-terraform#154
=> Revert "Supporting custom project ID, outputting service account JSON"

nomad-gcp/nomad-autoscaler.tf, nomad-gcp/output.tf, nomad-gcp/variables.tf
This change allows the upstream module to pass in a specific project_id to target. It also outputs the service account key as a sensitive output, in addition to writing it to the filesystem, so it can be more easily consumed by a parent module.
This re-merge reintroduces these changes, and fixes a bug that stops the module from trying to get the key as an output when the key does not exist.
=> GCP Nomad Client - Additional Project Support and Key Output

shared/modules/tls/tls.tf
This was needed to run EKS `terraform init` on my new mac
=> Bump hashicorp/tls to work on m1 macs

README.md, nomad-aws/README.md, nomad-gcp/README.md
SERVER-2358
We were still referencing KOTS and the Nomad port
Removed KOTS and Nomad port references
Updated 4.0.0 references to 4.1.0
=> chore: Remove KOTS, Nomad port, and update to 4.1.0

nomad-aws/README.md, nomad-aws/output.tf, nomad-gcp/README.md, nomad-gcp/output.tf
Server customers may not recognize immediately where the generated base64 output from the Terraform stacks should be added w.r.t. the Helm values yaml: https://circleci.com/docs/server/installation/installation-reference/#all-values-yaml-options
A Server customer noted, ideally, it would be best if we (CircleCI) can help prepare a script to copy-paste these outputs to their Helm values.yaml .
This will avoid user errors from copy-pasting.
I think that may be something worth exploring.
However, in the meantime, we can definitely improve our documentation here, to let users know where these outputs are needed.
Hence, this PR adds the descriptions to the 3 required outputs from the TF stack.
We let users know where these outputs will be needed …
=> Add output descriptions for outputs used in Server 4.x Helm values

nomad-aws/README.md, nomad-aws/examples/basic/main.tf, nomad-aws/main.tf, nomad-aws/variables.tf, nomad-gcp/README.md, nomad-gcp/main.tf, nomad-gcp/variables.tf
[SERVER-2496] - Currently nomad machine images are hardcoded and unable to be modified without forking.
This PR abstracts the hardcoded values to variables so they can be modified more easily. 
[SERVER-2496]: https://circleci.atlassian.net/browse/SERVER-2496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SERVER-2496] Nomad machine images as variables

nomad-aws/main.tf, nomad-aws/template/nomad-startup.sh.tpl, nomad-aws/variables.tf, nomad-gcp/main.tf, nomad-gcp/templates/nomad-startup.sh.tpl, nomad-gcp/variables.tf
:gear: EXEC-3305
:white_check_mark: Updates Nomad to our latest forked version ahead of the next release
:question: Tested in EXECs AWS cluster
=> Use our latest patched version of nomad

README.md, nomad-aws/README.md, nomad-aws/nomad-autoscaler.tf, nomad-aws/template/nomad_nodegroup_iam_role_policy.tpl, nomad-aws/variables.tf
Jira: https://circleci.atlassian.net/browse/ONPREM-129
AWS requires the Nomad Autoscaler daemon to have a certain set of permissions associated with its EKS nodegroup IAM role. This PR attaches a policy to that role with the required permissions.
I've done some testing of this against our internal server-infrastructure to ensure that the policy gets created and associated with the EKS node group IAM role as expected: https://github.com/circleci/server-infrastructure/pull/22
=> Add permissions policy to the EKS nodegroup IAM role for Nomad Autoscaler [ONPREM-129]

README.md
In the 4.3 release we bumped the version of hashicorp/tls used which resolved the m1 issue. We no longer need to recommend this helper tool
=> m1-terraform-provider-helper is no longer needed

README.md
With the latest version of hashicorp/tls the m1 macbook helper and its documentation is not required.
With the latest version of hashicorp/tls the m1 macbook helper and its documentation is not required.
Removed documentation
=> Remove unused m1 macbook helper documentation

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/variables.tf
Rerun with SSH on Docker is currently broken on CircleCI Server >4.6.0.
Make IMDSv2 configurable with a default of `optional`.
Tested this works via a variable on a personal repository.
=> Add support for IMDSv2 configured via variable

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/template/nomad-startup.sh.tpl, nomad-aws/variables.tf, nomad-gcp/README.md, nomad-gcp/main.tf, nomad-gcp/templates/nomad-startup.sh.tpl, nomad-gcp/variables.tf
up till now we've used the circleci nomad image which we would like to move away from maintaining to lower our internal burden. this PR replaces the circleci image with nomad directly from hashicorp.
=> using nomad from hashi

nomad-aws/template/nomad_asg_policy.tpl
- Nomad AWS Autoscaling is not working due 403 error when evaluating the policy. 
- Added `autoscaling:DescribeInstanceRefreshes` in nomad IAM policy
=> ONPREM-2030 | update nomad autoscaler aws policy

nomad-aws/role.tf
- Nomad AWS IAM Role and Policy should only be created when nomad-server is enabled.  ( It was missed in https://github.com/CircleCI-Public/server-terraform/pull/204 )
- Added the condition
=> ONPREM-2030 | updated nomad role creation condition

nomad-aws/main.tf, nomad-aws/role.tf
**Role creation condition update for Nomad AWS**
- `"${var.basename}-circleci-nomad-clients-instance-role"` will be created only if nomad server is enabled and role is null
- Fixed the derivation for `nomad_client_instance_role` for the same above case
=> ONPREM | nomad role condition update

nomad-gcp/README.md, nomad-gcp/nomad-autoscaler.tf, nomad-gcp/versions.tf
- GCP provider version update to allow tags/labels  as default
=> ONPREM-1744 | update gcp provider version

nomad-aws/README.md, nomad-aws/variables.tf, nomad-gcp/README.md, nomad-gcp/variables.tf
- Job is getting "queued" and correct status is not being reported 
- Downgraded the version to working one `1.6.1-1`
=> Downgrading Nomad Version for GCP and AWS both

nomad-gcp/modules/nomad-server-gcp/templates/nomad-server-startup.sh.tpl, nomad-gcp/templates/nomad-startup.sh.tpl
- There is no circleci install, hence removed the circleci check
- Logs are not printing in color, hence removed log logic
- Now script will exist if Nomad Install is not successful
=> ONPREM-2220 | fix gcp install script

nomad-gcp/modules/nomad-server-gcp/templates/nomad-server-startup.sh.tpl
- `/etc/nomad/ssl` directory does not exists in `nomad-gcp`
- Added a `mkdir` command to create the dir
=> Creating Nomad SSL Directory in nomad-gcp

nomad-aws/README.md, nomad-aws/main.tf, nomad-aws/security_groups.tf
There is no explicit security group rule defined for Nomad Client in AWS provider. 
Added Explicit SG rule which allow Nomad Server/Client communication within VPC. This will safe keep the Nomad Clients from any external connection attempts.
=> ONPREM-2249 | Restrict nomad traffic within vpc for AWS Nomad

nomad-aws/README.md, nomad-gcp/README.md, nomad-gcp/main.tf, nomad-gcp/modules/nomad-server-gcp/server.tf
There is no firewall rule defined for Nomad Client and Server communication in GCP provider. 
Added Explicit firewall rule which allow Nomad Server/Client communication within Subnetwork configured for Nomad Client and Server. This will safe keep the Nomad Clients from any external connection attempts.
=> ONPREM-2249 | Restrict nomad traffic within vpc for GCP Nomad

nomad-aws/security_groups.tf
Added missing `[]` in AWS Security Group IAM for Nomad
=> ONPREM-2249 | typo fix added []

nomad-aws/examples/irsa/main.tf, nomad-aws/template/nomad-startup.sh.tpl
Rerun with SSH functionality has been broke when forcing **IMDSv2 on Nomad clients**, getting below error - 
- Added the token while calling metadata end points
=> ONPREM-2370 | Using token while calling Metadata endpoint

Makefile, nomad-gcp/README.md, nomad-gcp/examples/basic/main.tf, nomad-gcp/examples/docker_network/main.tf, nomad-gcp/examples/nomad-server/main.tf, nomad-gcp/main.tf, nomad-gcp/output.tf, nomad-gcp/servers.tf, nomad-gcp/tests/basic.tftest.hcl, nomad-gcp/variables.tf
Currently, `nomad-gcp` give the options to disable the mTLS creation for nomad communication. 
- Removed the options to disable the mTLS, it will be forced generation
- Added Test for the same
=> ONPREM-2273 | Remove option to disable mtls in GCP Nomad

nomad-aws/README.md, nomad-aws/output.tf
- Exposing Base64 encoded Nomad Client certs
=> ONPREM-2268 | exposing output value of Nomad client cert
